# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: war.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\twar.proto\x12\x07warzone\"O\n\x11SimulationRequest\x12\t\n\x01N\x18\x01 \x01(\x05\x12\t\n\x01M\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x05\x12\x16\n\x0esoldier_speeds\x18\x04 \x03(\x05\"/\n\x12SimulationResponse\x12\x19\n\x11simulation_output\x18\x01 \x03(\t2Z\n\x10WarzoneSimulator\x12\x46\n\x0bSimulateWar\x12\x1a.warzone.SimulationRequest\x1a\x1b.warzone.SimulationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'war_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SIMULATIONREQUEST']._serialized_start=22
  _globals['_SIMULATIONREQUEST']._serialized_end=101
  _globals['_SIMULATIONRESPONSE']._serialized_start=103
  _globals['_SIMULATIONRESPONSE']._serialized_end=150
  _globals['_WARZONESIMULATOR']._serialized_start=152
  _globals['_WARZONESIMULATOR']._serialized_end=242
# @@protoc_insertion_point(module_scope)
